---
title: "Lab 00 - Hello IDS!"
author: "Joseph AG Gooding"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

### Exercises 16-17

We set up the data frame. Edit the data below to include information about your team members. 

```{r setup-tibble}
# This is a comment and wont print
team_data <- tibble(
  name = c("Peter Rabbit", "brian ", "simon", 
           "peter", "leo"),
  github_username = c("PR37
                    ", " B67", "S56", 
                      "P99", "Leo27"), 
  colour = c("powderblue", "orange", "yellow", 
             "pink", "red"),
  hobby = c("Hopping", "rugby", "hockey", 
            "golf", "sailing"),
  favourite_number = c(2, 3, 4, 5, 27)
  )

team_data
```

### Exercise 18

We now work on visualising our data. 

```{r bar-plot}
p1 <- ggplot(data = team_data, 
             mapping = aes(x = github_username, 
                           y = favourite_number,
                           fill = colour), 
             ) +
   geom_col() +
   scale_fill_identity()
p1

```

Leo27 has the largest favourite number


